version: "3.9"
services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=leaderboards
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/data

  leaderboard:
    image: lunatech-leaderboards-leaderboard:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - appdata:/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_HOST=${KEYCLOAK_HOST}
      - KEYCLOAK_SECRET=${KEYCLOAK_SECRET}

volumes:
  dbdata:
  appdata: