quarkus:
  # Data source
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jdbc:
      url: jdbc:postgresql://db:5432/leaderboards?stringtype=unspecified

  # Security
  oidc:
    credentials:
      secret: ${KEYCLOAK_SECRET}
    client-id: leaderboards-backend
    tls:
      verification: required

  keycloak:
    policy-enforcer:
      enable: false

  # Swagger
  smallrye-openapi:
    security-scheme: oidc
    oidc-open-id-connect-url: ${KEYCLOAK_HOST}/auth/realms/lunatech/.well-known/openid-configuration
  swagger-ui:
    always-include: true
    oauth2-redirect-url: http://localhost:8080/q/swagger-ui/oauth2-redirect.html
    oauth-client-id: leaderboards-frontend
