quarkus:
  # Data source
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/leaderboards?stringtype=unspecified

  # Security
  oidc:
    credentials:
      secret: secret
    tls:
      verification: none

  oidc-client:
    auth-server-url: http://localhost:8081/realms/Quarkus
    credentials:
      secret: secret

  keycloak:
    devservices:
      enabled: true
      realm-path: quarkus-realm.json
      port: 8081

  # Swagger
  smallrye-openapi:
    security-scheme-name: SecurityScheme
    oidc-open-id-connect-url: http://localhost:8081/realms/Quarkus/.well-known/openid-configuration