quarkus:
  # Data source
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/leaderboards?stringtype=unspecified

  # Flyway
  flyway:
    clean-at-start: true
    migrate-at-start: true
    validate-on-migrate: true
    locations: "db/migration,db/sample"

  # Security
  oidc:
    auth-server-url: http://localhost:8081/auth/realms/Quarkus
    client-id: leaderboards-backend
    tls:
      verification: none

  keycloak:
    devservices:
      enabled: false

  # Swagger
  smallrye-openapi:
    security-scheme-name: SecurityScheme
    oidc-open-id-connect-url: http://localhost:8081/auth/realms/Quarkus/.well-known/openid-configuration

  log:
    category:
      "io.quarkus.oidc":
        level: DEBUG
