apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: leaderboards
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: leaderboards

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/lunatech-labs/*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: leaderboards
      server: https://kubernetes.default.svc

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

  roles:
    - name: full-access
      description: Developer privileges to my-project
      policies:
        - p, role:leaderboards, applications, create, leaderboards/*, allow
        - p, role:leaderboards, applications, delete, leaderboards/*, allow
        - p, role:leaderboards, applications, get, leaderboards/*, allow
        - p, role:leaderboards, applications, override, leaderboards/*, allow
        - p, role:leaderboards, applications, sync, leaderboards/*, allow
        - p, role:leaderboards, applications, update, leaderboards/*, allow
        - p, role:leaderboards, logs, get, leaderboards/*, allow
        - p, role:leaderboards, exec, create, leaderboards/*, allow
        - p, role:leaderboards, projects, get, leaderboards, allow
      groups:
        - project-leaderboards