quarkus:
  # Data source
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    jdbc:
      url: jdbc:${POSTGRES_URL}/leaderboards?stringtype=unspecified

  # Flyway
  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    locations: "db/migration"

  # Security
  oidc:
    client-id: leaderboards-backend
    tls:
      verification: required

  # Swagger
  smallrye-openapi:
    security-scheme: oidc
    oidc-open-id-connect-url: ${KEYCLOAK_HOST}/realms/lunatech/.well-known/openid-configuration
  swagger-ui:
    always-include: true
    oauth2-redirect-url: http://localhost:8080/q/swagger-ui/oauth2-redirect.html
    oauth-client-id: leaderboards-frontend

  # GraphQL
  smallrye-graphql-client:
    lunagraph:
      url: https://api-dev.lunatech.cloud/graphql

  # Building
  container-image:
    group: lunatech-labs
    name: lunatech-leaderboards
    registry: ghcr.io
    additional-tags: latest