apiVersion: v1
kind: Service
metadata:
  name: leaderboards-service
  namespace: leaderboards
spec:
  selector:
    app: leaderboards
    tier: container
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP