name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QUARKUS_APPLICATION_VERSION: ${{ github.run_number }}
      QUARKUS_CONTAINER_IMAGE_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
      QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Env var checks
      run: echo version - $QUARKUS_APPLICATION_VERSION; echo pushing - $QUARKUS_CONTAINER_IMAGE_PUSH; echo username - $QUARKUS_CONTAINER_IMAGE_USERNAME;
    - name: Build and conditionally push container image with Maven
      run: ./mvnw -B package -Dquarkus.container-image.build=true
